baseURL = 'http://foresterorg.github.io/'
languageCode = 'en-us'
title = 'Forester Project'
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[menu]

  [[menu.main]]
    identifier = "getting-started"
    name = "Getting Started"
    pageRef = '/getting-started'
    weight = 10
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    pre = "<i class='fa fa-heart'></i>"
    url = "/docs/"
    weight = 20
